import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create antam app',
  description: 'Generated by create antam app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  )
}
